sudo: required
dist: trusty

services:
    - docker

language: go

go:
  -  1.8

before_install:
    - sudo apt-get update
    - sudo apt-get install -y docker-engine liblxc1 lxc-dev lxc
    - sudo apt-get install -y qemu
    - ./scripts/install_rkt.sh
    - ./scripts/install_consul.sh
    - ./scripts/install_vault.sh

install:
  - pwd
  - ls /home/travis/gopath/src/github.com/
  - mkdir -p /home/travis/gopath/src/github.com/
  - mv /home/travis/gopath/src/github.com/samber /home/travis/gopath/src/github.com/hashicorp
  - cd /home/travis/gopath/src/github.com/hashicorp/nomad
  - pwd
  - make bootstrap

script:
  - docker run -d --name consul -p 8400:8400 -p 8500:8500 consul agent -dev -bind=127.0.0.1 -client=0.0.0.0
  - make travis
