sudo: required
dist: trusty

services:
    - docker

language: go

go:
  -  1.8

before_install:
    - mkdir -p /home/travis/gopath/src/github.com/hashicorp
#    - ln -s /home/travis/gopath/src/github.com/samber/nomad /home/travis/gopath/src/github.com/hashicorp/nomad
    - mv /home/travis/gopath/src/github.com/samber /home/travis/gopath/src/github.com/hashicorp
    - ls /home/travis/gopath/src/github.com/
    - cd /home/travis/gopath/src/github.com/hashicorp/nomad
    - sudo apt-get update
    - sudo apt-get install -y docker-engine liblxc1 lxc-dev lxc
    - sudo apt-get install -y qemu
    - ./scripts/install_rkt.sh
    - ./scripts/install_consul.sh
    - ./scripts/install_vault.sh

install:
  - cd /home/travis/gopath/src/github.com/hashicorp/nomad
  - pwd
  - make bootstrap

script:
  - make travis
